name: ClearChat
version: 1.0.0
main: me.athena222.clearchat.Main
authors: [Athena222, Pr0totype2]
description: Clear your servers chat the professional way!
website: https://www.spigotmc.org/resources/clearchat.15985/

commands:
   clearchat:
     description: Clear Chat!
     usage: /clearchat
     aliases: [cc]

permissions:     
   clearchat.use:
     description: Gives access to /clearchat
     default: op
   clearchat.reload:
     description: Gives access to /clearchat reload
     default: op  
   clearchat.me:
     description: Gives access to /clearchat me
     default: op
   clearchat.player:
     description: Gives access to /clearchat <player>
     default: op